# Generated by Django 3.1.4 on 2021-07-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.user')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='user_profile',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='entries.userprofile'),
            preserve_default=False,
        ),
    ]
