# Generated by Django 3.1.4 on 2021-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_review_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='credibility',
        ),
        migrations.AddField(
            model_name='entry',
            name='short_url',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
