# Generated by Django 3.1.4 on 2021-08-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210728_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Health', 'Health'), ('Politics', 'Politics'), ('History', 'History'), ('Education', 'Education'), ('Sports', 'Sports'), ('Business', 'Business'), ('Science', 'Science'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.URLField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='review',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
    ]
