# Generated by Django 3.1.4 on 2021-08-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20210803_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='fact',
            field=models.CharField(max_length=300),
        ),
    ]
