# Generated by Django 3.1.4 on 2021-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20210812_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='normal_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fact',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=400),
        ),
    ]
