# Generated by Django 3.1.4 on 2021-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='expertise',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (0, 0)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
